### ISSUE TITLE
Works only on articles that don't already have "utm_medium" in url

### ISSUE THREAD

**Issue by LasseMoench** [ol3k/azweb_decrypt#1]
If there is already a utm_medium parameter, the second one will be ignored. I'll make a pull request if I find the time :)

Example:
https://www.aachener-nachrichten.de/lokales/aachen/aachen-ordnungsamt-reagiert-auf-beschwerden-mehr-bettler-unterwegs_aid-38812579?utm_source=facebook&utm_medium=instant-message <- this works

https://www.aachener-nachrichten.de/lokales/aachen/aachen-ordnungsamt-reagiert-auf-beschwerden-mehr-bettler-unterwegs_aid-38812579?utm_source=facebook&utm_medium=social?utm_medium=instant-message <- this was produced by the plugin, doesn't work

**Comment by ol3k** [comment]
I committed a change to remove all URL parameters before adding utm_medium

should work now with all links, I will change extension later on.

**Comment by LasseMoench** [comment]
Sounds great, thanks for providing this useful extension!

**Comment by ol3k** [comment]
fixed in 4431ea4
